In [2]:
import sys
sys.path.append("..")

import tensorflow as tf

In [3]:
import augmentation

In [5]:
augmentation.Mixup

augmentation.Mixup

In [7]:
a = tf.constant([[1, 2, 3],[4, 5, 6]], tf.int32)
b = tf.constant([1, 2], tf.int32)

a.shape, b.shape

(TensorShape([2, 3]), TensorShape([2]))

In [9]:
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [10]:
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [8]:
tf.tile(a, b)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]], dtype=int32)>

In [11]:
c = tf.constant([1, 3], tf.int32)
tf.tile(a, c)

<tf.Tensor: shape=(2, 9), dtype=int32, numpy=
array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]], dtype=int32)>

In [19]:
tf.tile(tf.reshape(tf.range(10), (1, -1)), tf.constant([1, 2], tf.int32))

<tf.Tensor: shape=(1, 20), dtype=int32, numpy=
array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],
      dtype=int32)>

In [20]:
tf.reshape(tf.range(10), (1, -1))

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>

In [21]:
tf.expand_dims(tf.range(10), axis=0)

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], dtype=int32)>

In [26]:
BATCH_SIZE = 8
N_FEATURES = 21
FEATURE_DIM = 3

batch = tf.tile(
    tf.expand_dims(tf.range(BATCH_SIZE), axis=1),
    tf.constant([1, FEATURE_DIM], tf.int32)
)

batch

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]], dtype=int32)>

In [29]:
tf.random.shuffle(batch)

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]], dtype=int32)>

In [36]:
tf.expand_dims(
    tf.expand_dims(tf.range(BATCH_SIZE), axis=1),
    axis=2
)

<tf.Tensor: shape=(8, 1, 1), dtype=int32, numpy=
array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]]], dtype=int32)>

In [39]:
tf.tile(
    tf.expand_dims(
        tf.expand_dims(tf.range(BATCH_SIZE), axis=1),
        axis=2
    ),
    tf.constant([1, N_FEATURES, FEATURE_DIM], tf.int32)
)

<tf.Tensor: shape=(8, 21, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 

In [41]:
tf.random.shuffle(
    tf.tile(
        tf.expand_dims(
            tf.expand_dims(tf.range(BATCH_SIZE), axis=1),
            axis=2
        ),
        tf.constant([1, N_FEATURES, FEATURE_DIM], tf.int32)
    ),
    seed=26
)

<tf.Tensor: shape=(8, 21, 3), dtype=int32, numpy=
array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 

In [42]:
import numpy as np

In [73]:
for i in range(10):
    print(tf.random.stateless_binomial(
        shape=[2], seed=[123, 456], counts=[1, 1], probs=[0.5]
    ))

tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)


In [72]:
np.random.binomial(n=1, p=0.5, size=(8, 13))

array([[1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1]])

In [ ]:
shape = [3, 4, 3, 4, 2]


In [144]:
batch

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]], dtype=int32)>

In [150]:
shape = batch.shape
seed = 1000
seeds = tf.random.uniform(shape=(2,), minval=0, maxval=seed, dtype=tf.int32, seed=seed) #.numpy().tolist()
counts = 1
probs = 0.5

x = tf.random.stateless_binomial(shape, seeds, counts, probs)
print(x)
print(tf.reduce_mean(tf.cast(x, tf.float32)))

tf.Tensor(
[[0 1 1 0 0 0 0 1 1 1 1 0 1 1]
 [1 0 0 0 1 1 1 1 1 0 1 1 0 0]
 [0 1 0 0 0 0 1 0 1 0 0 1 1 1]
 [0 0 0 1 1 1 1 0 1 0 0 0 1 0]
 [1 0 1 1 1 0 1 0 0 0 1 1 1 1]
 [1 1 1 1 1 0 0 0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1 1 1 0 0 0 0 1]
 [0 0 0 0 1 0 1 1 1 1 0 1 0 0]], shape=(8, 14), dtype=int32)
tf.Tensor(0.49107143, shape=(), dtype=float32)


In [151]:
1 - x

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1]], dtype=int32)>

In [152]:
seed

1000

In [159]:
shuffled_batch = tf.random.shuffle(batch, seed=seed)
shuffled_batch

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], dtype=int32)>

In [160]:
batch * x

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [0, 2, 0, 0, 0, 0, 2, 0, 2, 0, 0, 2, 2, 2],
       [0, 0, 0, 3, 3, 3, 3, 0, 3, 0, 0, 0, 3, 0],
       [4, 0, 4, 4, 4, 0, 4, 0, 0, 0, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 0, 0, 0, 5, 0, 5, 0, 0, 0],
       [0, 6, 0, 0, 0, 0, 6, 6, 6, 0, 0, 0, 0, 6],
       [0, 0, 0, 0, 7, 0, 7, 7, 7, 7, 0, 7, 0, 0]], dtype=int32)>

In [161]:
shuffled_batch * (1 - x)

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[5, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [6, 0, 6, 6, 6, 6, 0, 6, 0, 6, 6, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 3, 0, 0, 0, 3, 0, 3, 3, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 4, 4, 0, 4, 0, 4, 4, 4],
       [7, 0, 7, 7, 7, 7, 0, 0, 0, 7, 7, 7, 7, 0],
       [2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 2, 2]], dtype=int32)>

In [162]:
batch * x + shuffled_batch * (1 - x)

<tf.Tensor: shape=(8, 14), dtype=int32, numpy=
array([[5, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 5, 0, 0],
       [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0],
       [6, 2, 6, 6, 6, 6, 2, 6, 2, 6, 6, 2, 2, 2],
       [1, 1, 1, 3, 3, 3, 3, 1, 3, 1, 1, 1, 3, 1],
       [4, 3, 4, 4, 4, 3, 4, 3, 3, 3, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 4, 4, 4, 5, 4, 5, 4, 4, 4],
       [7, 6, 7, 7, 7, 7, 6, 6, 6, 7, 7, 7, 7, 6],
       [2, 2, 2, 2, 7, 2, 7, 7, 7, 7, 2, 7, 2, 2]], dtype=int32)>

## Augmentation Layers

In [1]:
import sys
sys.path.append("..")

import tensorflow as tf

In [2]:
import augmentation

In [3]:
BATCH_SIZE = 8
N_FEATURES = 5

batch = tf.tile(
    tf.expand_dims(tf.range(1, BATCH_SIZE+1), axis=1),
    tf.constant([1, N_FEATURES], tf.int32)
)

batch

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8]], dtype=int32)>

In [4]:
nested_batch = {"key1": batch, "key2": batch}
nested_batch

{'key1': <tf.Tensor: shape=(8, 5), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8]], dtype=int32)>,
 'key2': <tf.Tensor: shape=(8, 5), dtype=int32, numpy=
 array([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8]], dtype=int32)>}

In [5]:
cutmix_layer = augmentation.CutMix(probability=0.5, seed=1000)

In [6]:
cutmix_output = cutmix_layer(nested_batch)
cutmix_output

{'key1': <tf.Tensor: shape=(8, 5), dtype=int32, numpy=
 array([[3, 1, 1, 1, 3],
        [5, 2, 2, 5, 5],
        [6, 6, 3, 6, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 2, 5, 2],
        [1, 6, 6, 6, 1],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8]], dtype=int32)>,
 'key2': <tf.Tensor: shape=(8, 5), dtype=int32, numpy=
 array([[3, 1, 1, 1, 3],
        [5, 2, 2, 5, 5],
        [6, 6, 3, 6, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 2, 5, 2],
        [1, 6, 6, 6, 1],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8]], dtype=int32)>}

In [14]:
shuffled_index = tf.random.shuffle(tf.range(BATCH_SIZE), seed=42)
shuffled_index

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 6, 2, 3, 0, 4, 5, 7], dtype=int32)>

In [15]:
shuffled_index.numpy().tolist()

[1, 6, 2, 3, 0, 4, 5, 7]

In [34]:
d = {"3": "trois", "4": 4, "5": 5}
type(d) is dict, isinstance(d, dict)

(True, True)

In [38]:
d

{'3': 'trois', '4': 4, '5': 5}

In [37]:
for key in d.keys():
    print(key)

3
4
5


In [35]:
d

{'3': 'trois', '4': 4, '5': 5}

In [36]:
d[next(iter(d))]

'trois'

In [23]:
isinstance(batch, tf.Tensor)

True

In [22]:
batch

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8]], dtype=int32)>

In [17]:
tf.gather(batch, indices=shuffled_index)

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8]], dtype=int32)>

In [4]:
cutmix_layer = augmentation.CutMix(probability=0.5, seed=1000)
# mixup_layer = augmentation.Mixup(alpha=0.7, seed=1000)

In [5]:
cutmix_batch = cutmix_layer(batch)
cutmix_batch

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[3, 1, 1, 1, 3],
       [5, 2, 2, 5, 5],
       [6, 6, 3, 6, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 2, 5, 2],
       [1, 6, 6, 6, 1],
       [7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8]], dtype=int32)>

In [6]:
cutmix_batch = cutmix_layer(batch)
cutmix_batch

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[6, 1, 6, 1, 1],
       [2, 1, 1, 2, 1],
       [7, 7, 7, 3, 7],
       [4, 2, 2, 4, 4],
       [4, 4, 5, 5, 5],
       [5, 5, 6, 6, 5],
       [8, 8, 7, 7, 8],
       [8, 3, 3, 8, 3]], dtype=int32)>

In [7]:
cutmix_batch = cutmix_layer(batch)
cutmix_batch

<tf.Tensor: shape=(8, 5), dtype=int32, numpy=
array([[4, 1, 4, 1, 1],
       [2, 3, 2, 2, 3],
       [3, 7, 3, 7, 3],
       [4, 4, 2, 2, 2],
       [1, 1, 1, 1, 5],
       [6, 8, 6, 8, 8],
       [5, 5, 5, 7, 5],
       [6, 8, 6, 6, 6]], dtype=int32)>